name: Manual
on:
    workflow_dispatch:
        inputs:
            greeting:
                type: string
                default: Hello
                required: true
                description: A cheerful word
jobs:
    set-summary:
        runs-on: windows-latest
        steps:
            - run: echo "${{ github.event.inputs.user_input }}"

    runs:
        needs: set-summary
        runs-on: windows-latest
        steps:
            - run: echo "${{inputs.geeting}}"